name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.13'
  # renovate: datasource=pypi depName=uv
  UV_VERSION: '0.5.12'

jobs:
  linux:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: [x86_64, aarch64]
        manylinux: [auto, musllinux_1_1]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Build wheels
        uses: PyO3/maturin-action@ea5bac0f1ccd0ab11c805e2b804bfcb65dac2eab # v1
        with:
          target: ${{ matrix.target }}
          manylinux: ${{ matrix.manylinux }}
          args: --release --out dist
          sccache: 'true'

      - name: Upload wheels
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: wheels-linux-${{ matrix.target }}-${{ matrix.manylinux }}
          path: dist

  windows:
    runs-on: windows-2025
    strategy:
      matrix:
        target: [x64, aarch64]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Build wheels
        uses: PyO3/maturin-action@ea5bac0f1ccd0ab11c805e2b804bfcb65dac2eab # v1
        with:
          # Recent versions (last one tested 1.7.8) lead to failures on Windows aarch64, so forcing the version for now.
          maturin-version: '1.7.4'
          target: ${{ matrix.target }}
          args: --release --out dist
          sccache: 'true'

      - name: Upload wheels
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: wheels-windows-${{ matrix.target }}
          path: dist

  macos:
    runs-on: macos-15
    strategy:
      matrix:
        target: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Build wheels
        uses: PyO3/maturin-action@ea5bac0f1ccd0ab11c805e2b804bfcb65dac2eab # v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist
          sccache: 'true'

      - name: Upload wheels
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: wheels-macos-${{ matrix.target }}
          path: dist

  sdist:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Build sdist
        uses: PyO3/maturin-action@ea5bac0f1ccd0ab11c805e2b804bfcb65dac2eab # v1
        with:
          command: sdist
          args: --out dist

      - name: Upload sdist
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: wheels-sdist
          path: dist

  publish:
    name: Publish
    runs-on: ubuntu-24.04
    needs: [linux, windows, macos, sdist]
    environment: pypi
    permissions:
      id-token: write
      contents: write
      attestations: write
    if: ${{ github.event_name == 'release' }}
    steps:
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@7668571508540a607bdfd90a87a560489fe372eb # v2
        with:
          subject-path: 'wheels-*/*'

      - name: Publish to PyPI
        uses: PyO3/maturin-action@ea5bac0f1ccd0ab11c805e2b804bfcb65dac2eab # v1
        with:
          command: upload
          args: --non-interactive --skip-existing wheels-*/*

  publish-docs:
    runs-on: ubuntu-24.04
    needs: publish
    permissions:
      contents: write
    if: ${{ github.event_name == 'release' }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Install uv
        uses: astral-sh/setup-uv@887a942a15af3a7626099df99e897a18d9e5ab3a # v5
        with:
          version: ${{ env.UV_VERSION }}

      - name: Install Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Deploy documentation
        run: uv run --only-group docs mkdocs gh-deploy --force
