{
 "title": "Validator Consensus Dashboard",
 "tags": [
  "consensus-vote-indexer",
  "extension-vote-indexer"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<!-- Main content -->\n<div style=\"display: flex; justify-content: space-between; align-items: center;\">\n  <!-- H2 with a link -->\n   <a href=\"https://github.com/cosmostation/cvms\" target=\"_blank\" style=\"text-decoration: none; color: inherit;\">\n    <h2 style=\"margin-right: 10px;\">Cosmos Validator Monitoring Service (CVMS) 🌌 🔭</h2>\n  </a> \n  <!-- \"Powered by Cosmostation\" on the right -->\n  <div style=\"display: flex; align-items: center;\">\n    <a href=\"https://cosmostation.io\" target=\"_blank\" style=\"text-decoration: none; color: inherit;\">\n        <span>Powered by Cosmostation </span>\n        <img src=\"https://raw.githubusercontent.com/cosmostation/chainlist/refs/heads/main/resource/cosmostation/cosmostation_color.svg\" alt=\"Logo\" style=\"height: 30px; margin-left: 5px;\">\n    </a>\n  </div>\n</div>\n\n<!-- Paragraph below the header -->\n<p>\n  The Cosmos Validator Monitoring Service (CVMS) is an open-source, integrated monitoring system designed for validators and network in the Cosmos app chain ecosystem.<br/>\n  This public dashboard is part of the beta launch, with the open-source repository coming soon.\n</p>\n<p>\n  <a href=\"https://public-cosmos-vms.cosmostation.io/d/be37h6ce99dz4e/network-duty-dashboard?from=now-30m\" target=\"_blank\" style=\"text-decoration: none; color: #1E90FF;\">\n    👉 Validator Duty Overview Click Here\n  </a> \n  <a href=\"https://public-cosmos-vms.cosmostation.io\" target=\"_blank\" style=\"text-decoration: none; color: #1E90FF;\">\n    👉 Validator Consensus Overview Click Here\n  </a> \n</p>"
   }
  },
  {
   "title": "Validator Golden Timer",
   "type": "table",
   "description": "The golden time means you should recover back up in consensus in specific duration. if not, your validator node will be jailed by onchain parameter ",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "  sum without (proposer_address, validator_consensus_address, validator_opeartor_address, instance, job, package, service) (\n      ceil(cvms_uptime_signed_blocks_window * (1 - cvms_uptime_min_signed_per_window))\n    - on (chain, chain_id) group_right ()\n      cvms_uptime_missed_blocks_counter\n  )\n* on (chain_id) group_left () (min by (chain_id) (60 / delta(cvms_block_height[1m])))"
    }
   ]
  },
  {
   "title": "Mainnet Validator Consensus Vote Status",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 34, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": " -- Get the latest 100 blocks for mainnet\nWITH latest_blocks_per_validator AS (\n  SELECT\n    vidx.height,\n    vidx.status,\n    concat(ci.chain_name, '-', ci.chain_id, '-', vi.moniker) as validator,\n    ROW_NUMBER() OVER (PARTITION BY vidx.validator_hex_address_id ORDER BY vidx.height DESC) as row_num\n  FROM\n    voteindexer vidx\n  JOIN\n    meta.chain_info ci ON vidx.chain_info_id = ci.id\n  JOIN\n    meta.validator_info vi ON vidx.validator_hex_address_id = vi.id\n  WHERE ci.mainnet = true     \n)\nSELECT\n  height,\n  status,\n  validator\nFROM\n  latest_blocks_per_validator\nWHERE\n  row_num <= 100\nORDER BY\n  validator ASC, height DESC;\n  \n "
    }
   ]
  },
  {
   "title": "Testnet Validator Consensus Vote Status",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "rawSql": "  -- Get the latest 100 blocks for testnet\nWITH latest_blocks_per_validator AS (\n  SELECT\n    vidx.height,\n    vidx.status,\n    concat(ci.chain_name, '-', ci.chain_id, '-', vi.moniker) as validator,\n    ROW_NUMBER() OVER (PARTITION BY vidx.validator_hex_address_id ORDER BY vidx.height DESC) as row_num\n  FROM\n    voteindexer vidx\n  JOIN\n    meta.chain_info ci ON vidx.chain_info_id = ci.id\n  JOIN\n    meta.validator_info vi ON vidx.validator_hex_address_id = vi.id\n  WHERE ci.mainnet = false     \n)\nSELECT\n  height,\n  status,\n  validator\nFROM\n  latest_blocks_per_validator\nWHERE\n  row_num <= 100\nORDER BY\n  validator ASC, height DESC;"
    }
   ]
  },
  {
   "title": "Validator Extension Vote Status",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "rawSql": "-- Get the latest 100 blocks for ve\nWITH latest_blocks_per_validator AS (\n  SELECT\n    veidx.height,\n    veidx.status,\n    veidx.vote_extension_length as ve_length,\n    concat(ci.chain_name, '-', ci.chain_id ,'-', vi.moniker) as validator,\n    ROW_NUMBER() OVER (PARTITION BY veidx.validator_hex_address_id ORDER BY veidx.height DESC) as row_num\n  FROM\n    veindexer veidx\n  JOIN\n    meta.chain_info ci ON veidx.chain_info_id = ci.id\n  JOIN\n    meta.validator_info vi ON veidx.validator_hex_address_id = vi.id\n)\nSELECT\n  height,\n  status,\n  validator,\n  ve_length\nFROM\n  latest_blocks_per_validator\nWHERE\n  row_num <= 100\nORDER BY\n  validator ASC, height DESC;\n  \n"
    }
   ]
  }
 ]
}