name: Python API
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  python_package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, macos-14, macos-15]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Build pip package
        run: |
          python -m pip install --verbose .
      - name: Test installation
        run: |
          kiss_slam_pipeline --help
