function(LinkStaticLibrary target library)
  if(${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.24.0" AND NOT PLATFORM_EMSCRIPTEN AND NOT PLATFORM_LINUX)
	  target_link_libraries(${target} PUBLIC "$<LINK_LIBRARY:whole_archive,${library}>")
  else()
    target_link_libraries(${target} PUBLIC ${library})
    if(COMPILER_MSVC)
      target_link_options(${target} PUBLIC "LINKER:/WHOLEARCHIVE:$<TARGET_FILE:${library}>")
    elseif(COMPILER_CLANG AND PLATFORM_APPLE)
      target_link_options(${target} PUBLIC "LINKER:-force_load,$<TARGET_FILE:${library}>")
    else(COMPILER_CLANG OR COMPILER_GCC)
      target_link_options(${target} PUBLIC "LINKER:--whole-archive,$<TARGET_FILE:${library}>,--no-whole-archive")
    endif()
  endif()
endfunction()
