name: Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable corepack
        run: npm i -g --force corepack && corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - run: pnpm install
        env:
          CI: true

      - run: pnpm lint

  check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable corepack
        run: npm i -g --force corepack && corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'

      - run: pnpm install
        env:
          CI: true

      - run: pnpm check
        env:
          POSTGRES_URL: ''
          OPENAI_API_KEY: ''
          FIREWORKS_API_KEY: ''
          BLOB_READ_WRITE_TOKEN: ''
