// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckApps() {
    return window['go']['main']['App']['CheckApps']();
}

export function CheckNrfrUpdate() {
    return window['go']['main']['App']['CheckNrfrUpdate']();
}

export function GetAppVersion(arg1) {
    return window['go']['main']['App']['GetAppVersion'](arg1);
}

export function GetDevices() {
    return window['go']['main']['App']['GetDevices']();
}

export function InstallNrfr() {
    return window['go']['main']['App']['InstallNrfr']();
}

export function InstallShizuku() {
    return window['go']['main']['App']['InstallShizuku']();
}

export function SelectDevice(arg1) {
    return window['go']['main']['App']['SelectDevice'](arg1);
}

export function StartNrfr() {
    return window['go']['main']['App']['StartNrfr']();
}

export function StartShizuku() {
    return window['go']['main']['App']['StartShizuku']();
}

export function WindowClose() {
    return window['go']['main']['App']['WindowClose']();
}

export function WindowMaximise() {
    return window['go']['main']['App']['WindowMaximise']();
}

export function WindowMinimise() {
    return window['go']['main']['App']['WindowMinimise']();
}
