{
 "title": "Cosmos Ecosystem Validator Duty Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<!-- Main content -->\n<div style=\"display: flex; justify-content: space-between; align-items: center;\">\n  <!-- H2 with a link -->\n   <a href=\"https://github.com/cosmostation/cvms\" target=\"_blank\" style=\"text-decoration: none; color: inherit;\">\n    <h2 style=\"margin-right: 10px;\">Cosmos Validator Monitoring Service (CVMS) 🌌 🔭</h2>\n  </a> \n  <!-- \"Powered by Cosmostation\" on the right -->\n  <div style=\"display: flex; align-items: center;\">\n    <a href=\"https://cosmostation.io\" target=\"_blank\" style=\"text-decoration: none; color: inherit;\">\n        <span>Powered by Cosmostation </span>\n        <img src=\"https://raw.githubusercontent.com/cosmostation/chainlist/refs/heads/main/resource/cosmostation/cosmostation_color.svg\" alt=\"Logo\" style=\"height: 30px; margin-left: 5px;\">\n    </a>\n  </div>\n</div>\n\n<!-- Paragraph below the header -->\n<p>\n  The Cosmos Validator Monitoring Service (CVMS) is an open-source, integrated monitoring system designed for validators and network in the Cosmos app chain ecosystem.<br/>\n  This public dashboard is part of the beta launch, with the open-source repository coming soon.\n</p>\n<p>\n  <a href=\"https://public-cosmos-vms.cosmostation.io/d/be37h6ce99dz4e/network-duty-dashboard?from=now-30m\" target=\"_blank\" style=\"text-decoration: none; color: #1E90FF;\">\n    👉 Validator Duty Overview Click Here\n  </a> \n  <a href=\"https://public-cosmos-vms.cosmostation.io\" target=\"_blank\" style=\"text-decoration: none; color: #1E90FF;\">\n    👉 Validator Consensus Overview Click Here\n  </a> \n</p>"
   }
  },
  { "title": "Eventnonce Package", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Injective Eventnonce Difference Value",
   "type": "timeseries",
   "description": "Hide some validator who have value over 100",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(cvms_eventnonce_highest_nonce - on (chain_id) group_right cvms_eventnonce_nonce{chain_id='injective-1'}) without (job, instance, package)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gravity Eventnonce Difference Value",
   "type": "timeseries",
   "description": "Hide some validator who have value over 100",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 6 },
   "targets": [
    {
     "expr": "sum(cvms_eventnonce_highest_nonce - on (chain_id) group_right cvms_eventnonce_nonce{chain_id='gravity-bridge-3'}) without (job, instance, package)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sommelier Eventnonce Difference Value",
   "type": "timeseries",
   "description": "Hide some validator who have value over 100",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "sum(cvms_eventnonce_highest_nonce - on (chain_id) group_right cvms_eventnonce_nonce{chain_id='sommelier-3'}) without (job, instance, package)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Oracle Package", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Sei Oracle Status",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum((cvms_oracle_vote_window - on (chain_id) group_right cvms_oracle_miss_counter{chain_id='pacific-1'}) / on(chain_id) group_left cvms_oracle_vote_window) without (job, instance, package)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Umee Oracle Status",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum((cvms_oracle_vote_window - on (chain_id) group_right cvms_oracle_miss_counter{chain_id='umee-1'}) / on(chain_id) group_left cvms_oracle_vote_window) without (job, instance, package)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Yoda Package", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Band Yoda Status",
   "type": "stat",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cvms_yoda_status{chain_id=\"laozi-mainnet\"}) without (instance, job, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Axelar EVM Pacakge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Axelar EVM Maintainer Status",
   "type": "stat",
   "description": "only display inactive chains",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cvms_axelar_evm_maintainer_status{chain_id='axelar-dojo-1'} == 0) without (instance, job, instance)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}