//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinDepends.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinDepends.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display program information, version number, and copyright.
        /// </summary>
        internal static string About___ {
            get {
                return ResourceManager.GetString("About...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files|*.*.
        /// </summary>
        internal static string AllFilesFilter {
            get {
                return ResourceManager.GetString("AllFilesFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When checked, the module tree view will automatically expand to show modules as they are added.
        /// </summary>
        internal static string Auto_Expand {
            get {
                return ResourceManager.GetString("Auto Expand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri 11/15/2024  7:47:41.13 
        ///.
        /// </summary>
        internal static string BuildDate {
            get {
                return ResourceManager.GetString("BuildDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears the log window.
        /// </summary>
        internal static string Clear_Log_Window {
            get {
                return ResourceManager.GetString("Clear Log Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the active module session.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all modules in the tree view.
        /// </summary>
        internal static string Collapse_All {
            get {
                return ResourceManager.GetString("Collapse All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure or view program settings.
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the selection to the Clipboard as text.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the selection to the Clipboard as text.
        /// </summary>
        internal static string Copy_File_Name {
            get {
                return ResourceManager.GetString("Copy File Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the selection to the Clipboard as text.
        /// </summary>
        internal static string Copy_File_Names {
            get {
                return ResourceManager.GetString("Copy File Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the selection to the Clipboard as text.
        /// </summary>
        internal static string Copy_Function_Name {
            get {
                return ResourceManager.GetString("Copy Function Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the selection to the Clipboard as text.
        /// </summary>
        internal static string Copy_Function_Names {
            get {
                return ResourceManager.GetString("Copy Function Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the selection to the Clipboard as text.
        /// </summary>
        internal static string Copy_Text {
            get {
                return ResourceManager.GetString("Copy Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit program.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand and show all modules in the tree view.
        /// </summary>
        internal static string Expand_All {
            get {
                return ResourceManager.GetString("Expand All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find text in the log window.
        /// </summary>
        internal static string Find___ {
            get {
                return ResourceManager.GetString("Find...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue the last find operation in the log window.
        /// </summary>
        internal static string Find_Next {
            get {
                return ResourceManager.GetString("Find Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show module&apos;s full path in the module tree view and module list view.
        /// </summary>
        internal static string Full_Paths {
            get {
                return ResourceManager.GetString("Full Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FunctionIcons {
            get {
                object obj = ResourceManager.GetObject("FunctionIcons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight the matching item in the related view.
        /// </summary>
        internal static string Highlight_Matching_Export_Function {
            get {
                return ResourceManager.GetString("Highlight Matching Export Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight the matching item in the related view.
        /// </summary>
        internal static string Highlight_Matching_Import_Function {
            get {
                return ResourceManager.GetString("Highlight Matching Import Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight the matching item in the related view.
        /// </summary>
        internal static string Highlight_Matching_Module_In_List {
            get {
                return ResourceManager.GetString("Highlight Matching Module In List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight the matching item in the related view.
        /// </summary>
        internal static string Highlight_Module_In_Tree {
            get {
                return ResourceManager.GetString("Highlight Module In Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight the next instance of the selected module in module tree view.
        /// </summary>
        internal static string Highlight_Next_Instance {
            get {
                return ResourceManager.GetString("Highlight Next Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight the original instance of the selected module in module tree view.
        /// </summary>
        internal static string Highlight_Original_Instance {
            get {
                return ResourceManager.GetString("Highlight Original Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight the previous instance of the selected module in module tree view.
        /// </summary>
        internal static string Highlight_Previous_Instance {
            get {
                return ResourceManager.GetString("Highlight Previous Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup the selected function in the external help collection.
        /// </summary>
        internal static string Lookup_Function_in_External_Help {
            get {
                return ResourceManager.GetString("Lookup Function in External Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ModuleIcons {
            get {
                object obj = ResourceManager.GetObject("ModuleIcons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ModuleIconsAll {
            get {
                object obj = ResourceManager.GetObject("ModuleIconsAll", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open this module.
        /// </summary>
        internal static string mruListItem {
            get {
                return ResourceManager.GetString("mruListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a module session.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a module session.
        /// </summary>
        internal static string Open___ {
            get {
                return ResourceManager.GetString("Open...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file location for a selected module.
        /// </summary>
        internal static string Open_Module_Location {
            get {
                return ResourceManager.GetString("Open Module Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the properties for the selected items.
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the properties for the selected items.
        /// </summary>
        internal static string Properties___ {
            get {
                return ResourceManager.GetString("Properties...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh all module information for the active module session.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the active module session.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the active module session with a new name or type.
        /// </summary>
        internal static string Save_As___ {
            get {
                return ResourceManager.GetString("Save As...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SearchOrderIcons {
            get {
                object obj = ResourceManager.GetObject("SearchOrderIcons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all items in the current view.
        /// </summary>
        internal static string Select_All {
            get {
                return ResourceManager.GetString("Select All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display test data, for debug only build.
        /// </summary>
        internal static string Set_Test_Data {
            get {
                return ResourceManager.GetString("Set Test Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display resolved API set modules in module tree and list.
        /// </summary>
        internal static string Show_Resolved_API_sets {
            get {
                return ResourceManager.GetString("Show Resolved API sets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide the status bar.
        /// </summary>
        internal static string Status_Bar {
            get {
                return ResourceManager.GetString("Status Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the System Information dialog.
        /// </summary>
        internal static string System_Information___ {
            get {
                return ResourceManager.GetString("System Information...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide the toolbar.
        /// </summary>
        internal static string Toolbar {
            get {
                return ResourceManager.GetString("Toolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ToolBarIcons {
            get {
                object obj = ResourceManager.GetObject("ToolBarIcons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display undecorated C++ function names in the parent imports and exports view.
        /// </summary>
        internal static string Undecorate_C___Functions {
            get {
                return ResourceManager.GetString("Undecorate C++ Functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show module&apos;s full path in the module tree view and module list view.
        /// </summary>
        internal static string View_Full_Paths {
            get {
                return ResourceManager.GetString("View Full Paths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the selected modules in the external module viewer.
        /// </summary>
        internal static string View_Module_in_External_Viewer {
            get {
                return ResourceManager.GetString("View Module in External Viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the System Information dialog.
        /// </summary>
        internal static string View_System_Information {
            get {
                return ResourceManager.GetString("View System Information", resourceCulture);
            }
        }
    }
}
