# Requires -Modules Microsoft.Graph.Groups, PSWriteHTML

function Get-RecentEntraGroups {
    [CmdletBinding()]
    param (
        [int]$HoursBack = 1
    )
    
    $groups = [System.Collections.Generic.List[PSCustomObject]]::new()
    $filterDate = (Get-Date).AddHours(-$HoursBack).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    Write-Verbose "Filtering groups created after: $filterDate"
    
    # Build query components
    $baseUri = "https://graph.microsoft.com/v1.0/groups"
    $filter = "`$filter=createdDateTime ge $filterDate"
    $select = "`$select=id,displayName,description,createdDateTime"
    $orderBy = "`$orderby=createdDateTime desc"
    
    # URL encode the components
    $encodedFilter = [System.Web.HttpUtility]::UrlEncode($filter)
    $encodedSelect = [System.Web.HttpUtility]::UrlEncode($select)
    $encodedOrderBy = [System.Web.HttpUtility]::UrlEncode($orderBy)
    
    $uri = "$baseUri`?$encodedFilter&$encodedSelect&$encodedOrderBy"
    
    do {
        try {
            Write-Verbose "Executing request: $uri"
            $response = Invoke-MgGraphRequest -Uri $uri -Method GET -Headers @{
                "ConsistencyLevel" = "eventual"
                "Prefer" = "odata.maxpagesize=999"
            }
            
            if ($response.value) {
                $response.value | ForEach-Object { 
                    # Only add groups that are actually within our time window
                    $createdDate = [DateTime]$_.createdDateTime
                    if ($createdDate -ge (Get-Date).AddHours(-$HoursBack)) {
                        [void]$groups.Add($_)
                    }
                }
            }
            
            $uri = $response.'@odata.nextLink'
        }
        catch {
            Write-Error "Failed to retrieve groups: $_"
            Write-Verbose "Full error details: $($_.Exception.Message)"
            return $null
        }
    } while ($uri)
    
    Write-Verbose "Found $($groups.Count) groups created in the last $HoursBack hour(s)"
    Write-Output $groups
}

function Export-GroupDeletionReport {
    param(
        [Parameter(Mandatory)]
        $Groups,
        [Parameter(Mandatory)]
        [string]$OutputDir,
        [Parameter()]
        [string]$ReportName = "GroupDeletionReport"
    )
    
    $timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
    $htmlPath = Join-Path $OutputDir "$($ReportName)_$timestamp.html"
    $csvPath = Join-Path $OutputDir "$($ReportName)_$timestamp.csv"
    
    # Prepare report data
    $reportData = $Groups | Select-Object DisplayName, Description, @{
        Name = 'CreatedDateTime'
        Expression = { [DateTime]$_.CreatedDateTime }
    }
    
    # Export to CSV
    $reportData | Export-Csv -Path $csvPath -NoTypeInformation
    
    $metadata = @{
        GeneratedBy = $env:USERNAME
        GeneratedOn = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
        TotalGroups = $Groups.Count
    }
    
    New-HTML -Title "Group Deletion Report" -FilePath $htmlPath {
        New-HTMLSection -HeaderText "Deletion Summary" {
            New-HTMLPanel {
                New-HTMLText -Text @"
                <h3>Report Details</h3>
                <ul>
                    <li>Generated By: $($metadata.GeneratedBy)</li>
                    <li>Generated On: $($metadata.GeneratedOn)</li>
                    <li>Total Groups: $($metadata.TotalGroups)</li>
                </ul>
"@
            }
        }
        
        New-HTMLSection -HeaderText "Groups Pending Deletion" {
            New-HTMLTable -DataTable $reportData -ScrollX -Buttons @('copyHtml5', 'excelHtml5', 'csvHtml5') {
                New-TableCondition -Name 'CreatedDateTime' -ComparisonType string -Operator contains -Value '' -BackgroundColor White -Color Black
            }
        }
    }

    return @{
        CSVPath = $csvPath
        HTMLPath = $htmlPath
    }
}

function Remove-EntraGroupsSafely {
    param (
        [Parameter(Mandatory)]
        [object[]]$Groups
    )
    
    # Create output directory
    $outputDir = ".\GroupDeletionReports"
    $null = New-Item -ItemType Directory -Force -Path $outputDir

    # Generate initial reports
    $reports = Export-GroupDeletionReport -Groups $Groups -OutputDir $outputDir
    
    Write-Host "`nReports generated:" -ForegroundColor Green
    Write-Host "CSV Report: $($reports.CSVPath)" -ForegroundColor Green
    Write-Host "HTML Report: $($reports.HTMLPath)" -ForegroundColor Green

    # Display summary in console
    Write-Host "`nGroups to be deleted:" -ForegroundColor Yellow
    $Groups | Format-Table DisplayName, Description, @{
        Name = 'CreatedDateTime'
        Expression = { [DateTime]$_.CreatedDateTime }
    }

    # Ask for confirmation
    $confirmation = Read-Host "`nDo you want to proceed with deleting these groups? (Y/N)"
    
    if ($confirmation -eq 'Y') {
        $deleted = [System.Collections.ArrayList]::new()
        $failed = [System.Collections.ArrayList]::new()

        foreach ($group in $Groups) {
            try {
                $deleteUri = "https://graph.microsoft.com/v1.0/groups/$($group.id)"
                Invoke-MgGraphRequest -Uri $deleteUri -Method DELETE
                [void]$deleted.Add($group)
                Write-Host "Deleted group: $($group.DisplayName)" -ForegroundColor Green
            }
            catch {
                [void]$failed.Add(@{
                    Group = $group.DisplayName
                    Error = $_.Exception.Message
                })
                Write-Host "Failed to delete group $($group.DisplayName): $_" -ForegroundColor Red
            }
        }

        # Generate deletion results report
        $resultsReportName = "DeletionResults"
        New-HTML -Title "Group Deletion Results" -FilePath (Join-Path $outputDir "$($resultsReportName)_$(Get-Date -Format 'yyyyMMdd_HHmmss').html") {
            New-HTMLSection -HeaderText "Successfully Deleted Groups" {
                New-HTMLTable -DataTable $deleted -ScrollX
            }
            if ($failed.Count -gt 0) {
                New-HTMLSection -HeaderText "Failed Deletions" {
                    New-HTMLTable -DataTable $failed -ScrollX
                }
            }
        }
    }
    else {
        Write-Host "Operation cancelled by user." -ForegroundColor Yellow
    }
}

function Start-EntraGroupCleanup {
    [CmdletBinding()]
    param()
    
    # Add System.Web for URL encoding
    Add-Type -AssemblyName System.Web
    
    # Connect to Microsoft Graph if not already connected
    try {
        $context = Get-MgContext -ErrorAction Stop
        Write-Host "Connected to Microsoft Graph as: $($context.Account)" -ForegroundColor Green
    }
    catch {
        Write-Host "Please connect to Microsoft Graph first using Connect-MgGraph -Scopes 'Group.ReadWrite.All'" -ForegroundColor Yellow
        return
    }

    $recentGroups = Get-RecentEntraGroups -Verbose
    
    if ($null -eq $recentGroups) {
        Write-Host "No groups found or error occurred." -ForegroundColor Yellow
        return
    }
    
    if ($recentGroups.Count -eq 0) {
        Write-Host "No groups found created in the past hour." -ForegroundColor Green
        return
    }
    
    Remove-EntraGroupsSafely -Groups $recentGroups
}


Start-EntraGroupCleanup -Verbose