export default class RouterPath {
  static readonly INDEX_PAGE = 'pages/Index';
  static readonly MAIN_PAGE = 'pages/Main';
  static readonly ALBUM_RESULT_PAGE = 'pages/AlbumResultPage';
  static readonly CONTACT_RESULT_PAGE = 'pages/ContactResultPage';
  static readonly DEVICE_RESULT_PAGE = 'pages/DeviceResultPage';
  static readonly FILE_RESULT_PAGE = 'pages/FileResultPage';
  static readonly CAPTURE_PAGE = 'pages/CapturePage';
  static readonly CAPTURE_RESULT_PAGE = 'pages/CaptureResultPage';
  static readonly TEST_REPORT_PAGE = 'pages/TestReportPage';
  static readonly SECURE_RESULT_PAGE = 'pages/SecureResultPage';
}