//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Open5GSReference) DeepCopyInto(out *Open5GSReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Open5GSReference.
func (in *Open5GSReference) DeepCopy() *Open5GSReference {
	if in == nil {
		return nil
	}
	out := new(Open5GSReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Open5GSUser) DeepCopyInto(out *Open5GSUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Open5GSUser.
func (in *Open5GSUser) DeepCopy() *Open5GSUser {
	if in == nil {
		return nil
	}
	out := new(Open5GSUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Open5GSUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Open5GSUserList) DeepCopyInto(out *Open5GSUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Open5GSUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Open5GSUserList.
func (in *Open5GSUserList) DeepCopy() *Open5GSUserList {
	if in == nil {
		return nil
	}
	out := new(Open5GSUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Open5GSUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Open5GSUserSpec) DeepCopyInto(out *Open5GSUserSpec) {
	*out = *in
	out.Open5GS = in.Open5GS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Open5GSUserSpec.
func (in *Open5GSUserSpec) DeepCopy() *Open5GSUserSpec {
	if in == nil {
		return nil
	}
	out := new(Open5GSUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Open5GSUserStatus) DeepCopyInto(out *Open5GSUserStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Open5GSUserStatus.
func (in *Open5GSUserStatus) DeepCopy() *Open5GSUserStatus {
	if in == nil {
		return nil
	}
	out := new(Open5GSUserStatus)
	in.DeepCopyInto(out)
	return out
}
